# Generated by Django 4.2.6 on 2023-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentEmail', models.CharField(max_length=200)),
                ('studentName', models.TextField()),
                ('studentCourse', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
